/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "LAMM",
  "tagline": "MLLM Ecology",
  "url": "https://openlamm.github.io",
  "baseUrl": "/",
  "favicon": "/logo/LAMM-logo.png",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "plugins": [
    null,
    null
  ],
  "trailingSlash": false,
  "themes": [
    "@docusaurus/theme-live-codeblock"
  ],
  "clientModules": [
    "D:\\code\\openlamm.github.io\\src\\client\\define-ui-kit.js"
  ],
  "scripts": [
    {
      "src": "https://cdn.statuspage.io/se-v2.js"
    }
  ],
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "path": "docs/tutorial",
          "id": "tutorial",
          "routeBasePath": "/tutorial",
          "breadcrumbs": true,
          "showLastUpdateTime": false,
          "sidebarPath": "D:\\code\\openlamm.github.io\\sidebars-default.js"
        },
        "blog": false,
        "theme": {
          "customCss": [
            "D:\\code\\openlamm.github.io\\src\\css\\custom.css",
            "D:\\code\\openlamm.github.io\\src\\css\\api-reference.css"
          ]
        },
        "sitemap": {
          "ignorePatterns": [
            "/tags/**"
          ]
        },
        "googleTagManager": {
          "containerId": "GTM-5FDFFSS"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "/logo/LAMM-logo.png",
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "navbar": {
      "logo": {
        "href": "/",
        "src": "/logo/LAMM-logo-light.png",
        "srcDark": "/logo/LAMM-logo-dark.png",
        "alt": "LAMM",
        "height": "60px"
      },
      "items": [
        {
          "label": "Tutorial",
          "to": "tutorial",
          "position": "left"
        },
        {
          "label": "Datasets",
          "to": "/datasets",
          "position": "left"
        },
        {
          "label": "Models",
          "to": "/model_system_card",
          "position": "left"
        },
        {
          "label": "Leaderboards",
          "to": "/Leaderboards",
          "position": "left"
        },
        {
          "label": "Team",
          "to": "Team",
          "position": "left"
        },
        {
          "label": "Github",
          "to": "https://github.com/OpenGVLab/LAMM",
          "position": "left"
        }
      ],
      "hideOnScroll": false
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "liveCodeBlock": {
      "playgroundPosition": "bottom"
    }
  },
  "webpack": {},
  "baseUrlIssueBanner": true,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "headTags": [],
  "stylesheets": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
